// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAelrIPvZ4I_Npp7fXL6UY93kJP7S0IStg',
    appId: '1:873402932064:android:8aa04495c745efe406dc05',
    messagingSenderId: '873402932064',
    projectId: 'hotspot-project-41fbb',
    storageBucket: 'hotspot-project-41fbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqGR2tmL2BcKdFBQX7GkpvSVVsfSpEr8',
    appId: '1:873402932064:ios:534198455de6ebdf06dc05',
    messagingSenderId: '873402932064',
    projectId: 'hotspot-project-41fbb',
    storageBucket: 'hotspot-project-41fbb.appspot.com',
    androidClientId: '873402932064-qqpfnk1mfg222ee6f6gecjknidvf28tn.apps.googleusercontent.com',
    iosClientId: '873402932064-in11ka5h2rti6tma0s247lmuv53sfrsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotspotProject',
  );
}
